### PR TITLE
python like decorators and line:column lexer errors

### PR DESCRIPTION
**Pull request by SablyTv**
Five things come with this commit:
1. Spread expression, which is supposed to spread out an array as arguments (check the "test.lang" file)
2. Optional parameters, using "*" before parameter name. Stars usually (in other languages) is used to get the pointer, so might be better to use syntax like below:
`fn readFiles(fileNames: []string= []): boolean {...}`
instead of
`fn readFiles(*fileNames: []string]): boolean {...}`
But the idea is that if the parameter is optional, we define it as a known value, and empty string array in this case.
3. Python like decorators, check "test.lang" to show how its done. But in essence you create a function that takes in another function as a parameter. You then decorate another function with that function name. Then when we call that function we simply call the other one instead, with the function as a parameter.
4. Another token type for functions.
5. Lexer errors with line and column.

### CODE REVIEW

**Comment by SablyTv** [comment]
It is in one commit as I did not expect to make a PR for it. Can split it up if needed :)
Was thinking, if we wanted to we could (later when working on the interprenter/compiler) check if a function has the parameters: (func: Function, *args: []any) this would mark it as Decorator friendly. Only those can be used as decorators.

**Comment by itsfuad** [comment]
Using * as optional mark is confusing. Instead you can use ? for that. 
`fn readFiles(fileNames?: []string]): boolean {...}` makes more sense.

**Comment by SablyTv** [comment]
> Using * as optional mark is confusing. Instead you can use ? for that. `fn readFiles(fileNames?: []string]): boolean {...}` makes more sense.

Yeah, good idea!

**Comment by SablyTv** [comment]
> Using * as optional mark is confusing. Instead you can use ? for that. `fn readFiles(fileNames?: []string]): boolean {...}` makes more sense.

Pushed update :)
Added a `expectSoft(...)` which only advances if the current token is correct. Returns no errors if its not the one we expected

**Pull request closed without merging**
